In [ ]:
from shapely.geometry import shape, Point
import geopandas as gpd
from shapely.wkt import loads
import googlemaps
import pandas as pd
import time

In [ ]:
#### getting centroid of distract shapes

df = gpd.read_file("district_shapes.csv")

df["GEOMETRY"] = df["GEOMETRY"].apply(loads)
gdf = gpd.GeoDataFrame(df, geometry="GEOMETRY", crs="EPSG:4326")

gdf["CENTROID"] = gdf.geometry.centroid
gdf["LATITUDE"] = gdf.centroid.y
gdf["LONGITUDE"] = gdf.centroid.x

gdf[["DISTRICT", "LATITUDE", "LONGITUDE", "CENTROID"]].to_csv("district_centroids.csv", index=False)

/var/folders/ld/7kd9zdp94hn6bgrktkf6kl_00000gp/T/ipykernel_49879/2512167148.py:12: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf["CENTROID"] = gdf.geometry.centroid
/var/folders/ld/7kd9zdp94hn6bgrktkf6kl_00000gp/T/ipykernel_49879/2512167148.py:13: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf["LATITUDE"] = gdf.centroid.y
/var/folders/ld/7kd9zdp94hn6bgrktkf6kl_00000gp/T/ipykernel_49879/2512167148.py:14: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf["LONGITUDE"] = gdf.centroid.x

In [7]:
!pip install googlemaps

Collecting googlemaps
  Downloading googlemaps-4.10.0.tar.gz (33 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests<3.0,>=2.20.0 in /Users/N507807/anaconda3/lib/python3.11/site-packages (from googlemaps) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/N507807/anaconda3/lib/python3.11/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/N507807/anaconda3/lib/python3.11/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/N507807/anaconda3/lib/python3.11/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/N507807/anaconda3/lib/python3.11/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2025.1.31)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py) ... done
  Created wheel for googlemaps: filename=googlemaps-4.10.0-py3-none-any.whl size=40713 sha256=98d3e1eebd5e80ed036106610f32100648c3d875c043e15e2ea62236f4dd6323
  Stored in directory: /Users/N507807/Library/Caches/pip/wheels/f1/09/77/3cc2f5659cbc62341b30f806aca2b25e6a26c351daa5b1f49a
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.10.0

In [15]:
# Function to get distance & time
def get_distance_time(origin, destination, mode="driving"):
    try:
        result = gmaps.distance_matrix(origin, destination, mode=mode)
        element = result["rows"][0]["elements"][0]
        return {
            "distance_km": element["distance"]["value"] / 1000 if "distance" in element else None,
            "duration_min": element["duration"]["value"] / 60 if "duration" in element else None
        }
    except Exception as e:
        print(f"Error for {origin}: {e}")
        return {"distance_km": None, "duration_min": None}

In [ ]:
#### Accessing goole maps api to get distances between locations
## There is a limit of requests in a month, but if we do postcode districts rather than postocdes (millions) we can get all of the distances for free

API_KEY = "AIzaSyC_-XN16qOwcB3bMXdfR7NFM99YA_bBHK0"
gmaps = googlemaps.Client(key=API_KEY)

df = pd.read_csv("district_centroids.csv")

# Airports
airports = {
    "Heathrow": "51.4700,-0.4543",
    #"Gatwick": "51.1537,-0.1821"
}

# Run for all districts
results = []

KeyboardInterrupt:

In [25]:
print(len(df), df['DISTRICT'].nunique(), len(results))

2843 2843 792

In [30]:
df[791:]

,DISTRICT,LATITUDE,LONGITUDE,CENTROID
791,TR27,50.181412,-5.395341,POINT (-5.395341329676645 50.18141218452463)
792,PH34,56.951699,-5.004414,POINT (-5.004413530409362 56.95169888728969)
793,LS88,53.765776,-1.500488,POINT (-1.5004878772654588 53.76577562391349)
794,LN5,53.110390,-0.575887,POINT (-0.5758872781878935 53.11039004235136)
795,ST17,52.777783,-2.058269,POINT (-2.0582687103244535 52.77778337373126)
...,...,...,...,...
2838,TN19,51.005338,0.406508,POINT (0.4065076555876216 51.00533752056215)
2839,WN7,53.496379,-2.520246,POINT (-2.520245714329329 53.49637920799733)
2840,EC4P,51.524679,-0.112322,POINT (-0.1123223990706168 51.52467924398244)
2841,HP22,51.833730,-0.798253,POINT (-0.7982525516020255 51.83373034108558)
2842,G14,55.879898,-4.352369,POINT (-4.352368933287201 55.87989835289352)

In [31]:
for _, row in df[791:].iterrows():
    origin = f"{row['LATITUDE']},{row['LONGITUDE']}"
    row_result = {"DISTRICT": row["DISTRICT"]}
    
    for airport_name, airport_loc in airports.items():
        row_result[f"{airport_name}_driving"] = get_distance_time(origin, airport_loc, "driving")
        row_result[f"{airport_name}_transit"] = get_distance_time(origin, airport_loc, "transit")
    
    results.append(row_result)
    time.sleep(0.5)  # To prevent rate limits

In [47]:
output_df = pd.DataFrame(results)
output_df

,DISTRICT,Heathrow_driving,Heathrow_transit
0,PE8,"{'distance_km': 161.08, 'duration_min': 117.21...","{'distance_km': None, 'duration_min': None}"
1,BB9,"{'distance_km': 386.185, 'duration_min': 243.8...","{'distance_km': 418.28, 'duration_min': 346.11..."
2,CH99,"{'distance_km': 333.104, 'duration_min': 209.65}","{'distance_km': 316.944, 'duration_min': 213.8..."
3,CT15,"{'distance_km': 165.976, 'duration_min': 120.0...","{'distance_km': 162.245, 'duration_min': 209.3..."
4,MK5,"{'distance_km': 93.87, 'duration_min': 73.55}","{'distance_km': 90.885, 'duration_min': 132.55}"
...,...,...,...
2839,TN19,"{'distance_km': 123.483, 'duration_min': 94.7}","{'distance_km': 105.902, 'duration_min': 186.7..."
2840,WN7,"{'distance_km': 318.969, 'duration_min': 205.0...","{'distance_km': 352.037, 'duration_min': 240.3}"
2841,EC4P,"{'distance_km': 30.041, 'duration_min': 58.35}","{'distance_km': 29.838, 'duration_min': 53.966..."
2842,HP22,"{'distance_km': 67.197, 'duration_min': 56.233...","{'distance_km': 62.995, 'duration_min': 135.75}"
2843,G14,"{'distance_km': 650.785, 'duration_min': 400.7...","{'distance_km': 681.049, 'duration_min': 408.7..."

In [ ]:
output_df.to_csv("uk_district_heathrow_distances.csv", index=False)

## removed district TR27 mannually from csv file as it had 2 rows
## note that driving distance is at the time of api call (Thurs 27th Feb around 11am)